import type { Template, TemplateSet } from './types'

// Templates de roasts en français
export const roastsFr: TemplateSet = {
  light: [
    { text: "{{target}}, même ta playlist focus s'endort à la 2ᵉ piste.", intensity: 'light' },
    { text: "{{target}}, ton Wi-Fi a plus d'excuses que toi.", intensity: 'light' },
    { text: "{{target}}, tu cliques 'J'accepte' plus vite que tu ne réfléchis.", intensity: 'light' },
    { text: "{{target}}, ton code compile par pitié, pas par logique.", intensity: 'light' },
    { text: "{{target}}, même ChatGPT a besoin d'une pause après tes questions.", intensity: 'light' },
    { text: "{{target}}, on a vu des tortues livrer plus vite.", intensity: 'light' },
    { text: "{{target}}, ta motivation a la durée de vie d'un yaourt.", intensity: 'light' },
    { text: "{{target}}, même ton chargeur USB a plus de watts que ta motivation.", intensity: 'light' },
    { text: "{{target}}, tu es le genre de personne qui met du ketchup sur du sushi.", intensity: 'light' },
    { text: "{{target}}, ton organisation ressemble à un tiroir de chaussettes.", intensity: 'light' },
    { text: "{{target}}, tu es plus lent qu'un escargot en grève.", intensity: 'light' },
    { text: "{{target}}, même les horloges arrêtées ont raison deux fois par jour.", intensity: 'light' },
    { text: "{{target}}, tu es le champion du monde de la procrastination.", intensity: 'light' },
    { text: "{{target}}, ton sens de l'orientation est légendaire... dans le mauvais sens.", intensity: 'light' },
    { text: "{{target}}, tu es plus prévisible qu'un épisode de télé-réalité.", intensity: 'light' },
    { text: "{{target}}, même ton GPS se perd avec toi.", intensity: 'light' },
    { text: "{{target}}, tu es le roi/la reine des excuses créatives.", intensity: 'light' },
    { text: "{{target}}, ton timing est parfait... pour rater les bonnes occasions.", intensity: 'light' },
    { text: "{{target}}, tu es plus efficace qu'un parapluie troué.", intensity: 'light' },
    { text: "{{target}}, même les plantes d'intérieur ont plus de vie que toi.", intensity: 'light' }
  ],
  medium: [
    { text: "{{target}}, tu cliques 'J'accepte' plus vite que tu ne réfléchis.", intensity: 'medium' },
    { text: "{{target}}, ton code compile par pitié, pas par logique.", intensity: 'medium' },
    { text: "{{target}}, même ChatGPT a besoin d'une pause après tes questions.", intensity: 'medium' },
    { text: "{{target}}, on a vu des tortues livrer plus vite.", intensity: 'medium' },
    { text: "{{target}}, ta PR préférée c'est 'Plus Rien'.", intensity: 'medium', context: 'gym' },
    { text: "{{target}}, même les PNJ ont plus d'initiative.", intensity: 'medium', context: 'gaming' },
    { text: "{{target}}, tu es le genre de personne qui met du ketchup sur du sushi.", intensity: 'medium' },
    { text: "{{target}}, ton organisation ressemble à un tiroir de chaussettes.", intensity: 'medium' },
    { text: "{{target}}, tu es plus lent qu'un escargot en grève.", intensity: 'medium' },
    { text: "{{target}}, même les horloges arrêtées ont raison deux fois par jour.", intensity: 'medium' },
    { text: "{{target}}, tu es le champion du monde de la procrastination.", intensity: 'medium' },
    { text: "{{target}}, ton sens de l'orientation est légendaire... dans le mauvais sens.", intensity: 'medium' },
    { text: "{{target}}, tu es plus prévisible qu'un épisode de télé-réalité.", intensity: 'medium' },
    { text: "{{target}}, même ton GPS se perd avec toi.", intensity: 'medium' },
    { text: "{{target}}, tu es le roi/la reine des excuses créatives.", intensity: 'medium' },
    { text: "{{target}}, ton timing est parfait... pour rater les bonnes occasions.", intensity: 'medium' },
    { text: "{{target}}, tu es plus efficace qu'un parapluie troué.", intensity: 'medium' },
    { text: "{{target}}, même les plantes d'intérieur ont plus de vie que toi.", intensity: 'medium' },
    { text: "{{target}}, tu es le spécialiste des solutions temporaires permanentes.", intensity: 'medium' },
    { text: "{{target}}, ton optimisme est contagieux... comme une maladie.", intensity: 'medium' }
  ],
  spicy: [
    { text: "{{target}}, même ChatGPT a besoin d'une pause après tes questions.", intensity: 'spicy', safe: true },
    { text: "{{target}}, on a vu des tortues livrer plus vite.", intensity: 'spicy', safe: true },
    { text: "{{target}}, tu es le genre de personne qui met du ketchup sur du sushi.", intensity: 'spicy', safe: true },
    { text: "{{target}}, ton organisation ressemble à un tiroir de chaussettes.", intensity: 'spicy', safe: true },
    { text: "{{target}}, tu es plus lent qu'un escargot en grève.", intensity: 'spicy', safe: true },
    { text: "{{target}}, même les horloges arrêtées ont raison deux fois par jour.", intensity: 'spicy', safe: true },
    { text: "{{target}}, tu es le champion du monde de la procrastination.", intensity: 'spicy', safe: true },
    { text: "{{target}}, ton sens de l'orientation est légendaire... dans le mauvais sens.", intensity: 'spicy', safe: true },
    { text: "{{target}}, tu es plus prévisible qu'un épisode de télé-réalité.", intensity: 'spicy', safe: true },
    { text: "{{target}}, même ton GPS se perd avec toi.", intensity: 'spicy', safe: true },
    { text: "{{target}}, tu es le roi/la reine des excuses créatives.", intensity: 'spicy', safe: true },
    { text: "{{target}}, ton timing est parfait... pour rater les bonnes occasions.", intensity: 'spicy', safe: true },
    { text: "{{target}}, tu es plus efficace qu'un parapluie troué.", intensity: 'spicy', safe: true },
    { text: "{{target}}, même les plantes d'intérieur ont plus de vie que toi.", intensity: 'spicy', safe: true },
    { text: "{{target}}, tu es le spécialiste des solutions temporaires permanentes.", intensity: 'spicy', safe: true },
    { text: "{{target}}, ton optimisme est contagieux... comme une maladie.", intensity: 'spicy', safe: true },
    { text: "{{target}}, tu es plus original qu'une photocopie de photocopie.", intensity: 'spicy', safe: true },
    { text: "{{target}}, même les miroirs se cassent en te regardant.", intensity: 'spicy', safe: true },
    { text: "{{target}}, tu es le Picasso de la médiocrité.", intensity: 'spicy', safe: true },
    { text: "{{target}}, ton charisme a la profondeur d'une flaque d'eau.", intensity: 'spicy', safe: true },
    { text: "{{target}}, tu es si nul que même les échecs ont honte de toi.", intensity: 'spicy', safe: false },
    { text: "{{target}}, ton niveau de compétence rivalise avec celui d'un caillou.", intensity: 'spicy', safe: false },
    { text: "{{target}}, tu es la preuve vivante que l'évolution peut faire marche arrière.", intensity: 'spicy', safe: false },
    { text: "{{target}}, même les virus informatiques ont plus de personnalité que toi.", intensity: 'spicy', safe: false },
    { text: "{{target}}, tu es si inutile que même les déchets recyclables te refusent.", intensity: 'spicy', safe: false },
    { text: "{{target}}, ton existence est une erreur de casting dans le film de la vie.", intensity: 'spicy', safe: false },
    { text: "{{target}}, tu es plus décevant qu'un film de super-héros de 2023.", intensity: 'spicy', safe: false },
    { text: "{{target}}, même les spams ont plus de valeur que tes opinions.", intensity: 'spicy', safe: false },
    { text: "{{target}}, tu es le champion olympique de l'échec.", intensity: 'spicy', safe: false },
    { text: "{{target}}, ton cerveau a la capacité de stockage d'un trombone.", intensity: 'spicy', safe: false }
  ]
}

// Templates de roasts en anglais
export const roastsEn: TemplateSet = {
  light: [
    { text: "{{target}}, even your focus playlist falls asleep at track 2.", intensity: 'light' },
    { text: "{{target}}, your WiFi has more excuses than you do.", intensity: 'light' },
    { text: "{{target}}, you click 'Accept' faster than you think.", intensity: 'light' },
    { text: "{{target}}, your code compiles out of pity, not logic.", intensity: 'light' },
    { text: "{{target}}, even ChatGPT needs a break after your questions.", intensity: 'light' },
    { text: "{{target}}, we've seen turtles deliver faster.", intensity: 'light' },
    { text: "{{target}}, your motivation has the lifespan of yogurt.", intensity: 'light' },
    { text: "{{target}}, even your USB charger has more watts than your motivation.", intensity: 'light' },
    { text: "{{target}}, you're the kind of person who puts ketchup on sushi.", intensity: 'light' },
    { text: "{{target}}, your organization looks like a sock drawer.", intensity: 'light' },
    { text: "{{target}}, you're slower than a snail on strike.", intensity: 'light' },
    { text: "{{target}}, even stopped clocks are right twice a day.", intensity: 'light' },
    { text: "{{target}}, you're the world champion of procrastination.", intensity: 'light' },
    { text: "{{target}}, your sense of direction is legendary... in the wrong way.", intensity: 'light' },
    { text: "{{target}}, you're more predictable than a reality TV show.", intensity: 'light' },
    { text: "{{target}}, even your GPS gets lost with you.", intensity: 'light' },
    { text: "{{target}}, you're the king/queen of creative excuses.", intensity: 'light' },
    { text: "{{target}}, your timing is perfect... for missing good opportunities.", intensity: 'light' },
    { text: "{{target}}, you're more effective than a holey umbrella.", intensity: 'light' },
    { text: "{{target}}, even houseplants have more life than you.", intensity: 'light' }
  ],
  medium: [
    { text: "{{target}}, you click 'Accept' faster than you think.", intensity: 'medium' },
    { text: "{{target}}, your code compiles out of pity, not logic.", intensity: 'medium' },
    { text: "{{target}}, even ChatGPT needs a break after your questions.", intensity: 'medium' },
    { text: "{{target}}, we've seen turtles deliver faster.", intensity: 'medium' },
    { text: "{{target}}, your favorite PR is 'Nothing More'.", intensity: 'medium', context: 'gym' },
    { text: "{{target}}, even NPCs have more initiative.", intensity: 'medium', context: 'gaming' },
    { text: "{{target}}, you're the kind of person who puts ketchup on sushi.", intensity: 'medium' },
    { text: "{{target}}, your organization looks like a sock drawer.", intensity: 'medium' },
    { text: "{{target}}, you're slower than a snail on strike.", intensity: 'medium' },
    { text: "{{target}}, even stopped clocks are right twice a day.", intensity: 'medium' },
    { text: "{{target}}, you're the world champion of procrastination.", intensity: 'medium' },
    { text: "{{target}}, your sense of direction is legendary... in the wrong way.", intensity: 'medium' },
    { text: "{{target}}, you're more predictable than a reality TV show.", intensity: 'medium' },
    { text: "{{target}}, even your GPS gets lost with you.", intensity: 'medium' },
    { text: "{{target}}, you're the king/queen of creative excuses.", intensity: 'medium' },
    { text: "{{target}}, your timing is perfect... for missing good opportunities.", intensity: 'medium' },
    { text: "{{target}}, you're more effective than a holey umbrella.", intensity: 'medium' },
    { text: "{{target}}, even houseplants have more life than you.", intensity: 'medium' },
    { text: "{{target}}, you're the specialist of permanent temporary solutions.", intensity: 'medium' },
    { text: "{{target}}, your optimism is contagious... like a disease.", intensity: 'medium' }
  ],
  spicy: [
    { text: "{{target}}, even ChatGPT needs a break after your questions.", intensity: 'spicy', safe: true },
    { text: "{{target}}, we've seen turtles deliver faster.", intensity: 'spicy', safe: true },
    { text: "{{target}}, you're the kind of person who puts ketchup on sushi.", intensity: 'spicy', safe: true },
    { text: "{{target}}, your organization looks like a sock drawer.", intensity: 'spicy', safe: true },
    { text: "{{target}}, you're slower than a snail on strike.", intensity: 'spicy', safe: true },
    { text: "{{target}}, even stopped clocks are right twice a day.", intensity: 'spicy', safe: true },
    { text: "{{target}}, you're the world champion of procrastination.", intensity: 'spicy', safe: true },
    { text: "{{target}}, your sense of direction is legendary... in the wrong way.", intensity: 'spicy', safe: true },
    { text: "{{target}}, you're more predictable than a reality TV show.", intensity: 'spicy', safe: true },
    { text: "{{target}}, even your GPS gets lost with you.", intensity: 'spicy', safe: true },
    { text: "{{target}}, you're the king/queen of creative excuses.", intensity: 'spicy', safe: true },
    { text: "{{target}}, your timing is perfect... for missing good opportunities.", intensity: 'spicy', safe: true },
    { text: "{{target}}, you're more effective than a holey umbrella.", intensity: 'spicy', safe: true },
    { text: "{{target}}, even houseplants have more life than you.", intensity: 'spicy', safe: true },
    { text: "{{target}}, you're the specialist of permanent temporary solutions.", intensity: 'spicy', safe: true },
    { text: "{{target}}, your optimism is contagious... like a disease.", intensity: 'spicy', safe: true },
    { text: "{{target}}, you're more original than a photocopy of a photocopy.", intensity: 'spicy', safe: true },
    { text: "{{target}}, even mirrors break when they look at you.", intensity: 'spicy', safe: true },
    { text: "{{target}}, you're the Picasso of mediocrity.", intensity: 'spicy', safe: true },
    { text: "{{target}}, your charisma has the depth of a puddle.", intensity: 'spicy', safe: true },
    { text: "{{target}}, you're so useless that even failures are ashamed of you.", intensity: 'spicy', safe: false },
    { text: "{{target}}, your skill level rivals that of a rock.", intensity: 'spicy', safe: false },
    { text: "{{target}}, you're living proof that evolution can go backwards.", intensity: 'spicy', safe: false },
    { text: "{{target}}, even computer viruses have more personality than you.", intensity: 'spicy', safe: false },
    { text: "{{target}}, you're so worthless that even recyclables reject you.", intensity: 'spicy', safe: false },
    { text: "{{target}}, your existence is a casting error in the movie of life.", intensity: 'spicy', safe: false },
    { text: "{{target}}, you're more disappointing than a 2023 superhero movie.", intensity: 'spicy', safe: false },
    { text: "{{target}}, even spam has more value than your opinions.", intensity: 'spicy', safe: false },
    { text: "{{target}}, you're the Olympic champion of failure.", intensity: 'spicy', safe: false },
    { text: "{{target}}, your brain has the storage capacity of a paperclip.", intensity: 'spicy', safe: false }
  ]
}

// Templates par contexte
export const contextTemplatesFr: Record<string, Template[]> = {
  gym: [
    { text: "{{target}}, ta PR préférée c'est 'Plus Rien'.", intensity: 'light', context: 'gym' },
    { text: "{{target}}, même les haltères se moquent de toi.", intensity: 'medium', context: 'gym' },
    { text: "{{target}}, tu es le roi/la reine des excuses de gym.", intensity: 'light', context: 'gym' },
    { text: "{{target}}, ton cardio consiste à monter les escalators.", intensity: 'medium', context: 'gym' },
    { text: "{{target}}, tu es plus mou qu'un élastique usagé.", intensity: 'light', context: 'gym' },
    { text: "{{target}}, même les tapis de course s'ennuient avec toi.", intensity: 'medium', context: 'gym' },
    { text: "{{target}}, tu es le spécialiste des 'repos actifs' de 30 minutes.", intensity: 'light', context: 'gym' },
    { text: "{{target}}, ton programme d'entraînement tient sur un Post-it.", intensity: 'medium', context: 'gym' },
    { text: "{{target}}, tu es plus flexible qu'un bâton de dynamite.", intensity: 'light', context: 'gym' },
    { text: "{{target}}, même les poids libres ont plus de liberté que toi.", intensity: 'medium', context: 'gym' }
  ],
  gaming: [
    { text: "{{target}}, même les PNJ ont plus d'initiative.", intensity: 'light', context: 'gaming' },
    { text: "{{target}}, tu es le roi/la reine du rage quit.", intensity: 'medium', context: 'gaming' },
    { text: "{{target}}, ton K/D ratio est plus bas que ton QI.", intensity: 'light', context: 'gaming' },
    { text: "{{target}}, même les bots jouent mieux que toi.", intensity: 'medium', context: 'gaming' },
    { text: "{{target}}, tu es le spécialiste des 'lag excuses'.", intensity: 'light', context: 'gaming' },
    { text: "{{target}}, ton skill cap est au niveau du sol.", intensity: 'medium', context: 'gaming' },
    { text: "{{target}}, tu es plus toxique qu'un déchet radioactif.", intensity: 'light', context: 'gaming' },
    { text: "{{target}}, même les noobs te donnent des leçons.", intensity: 'medium', context: 'gaming' },
    { text: "{{target}}, tu es le champion du monde de l'afk.", intensity: 'light', context: 'gaming' },
    { text: "{{target}}, ton gameplay ressemble à un glitch permanent.", intensity: 'medium', context: 'gaming' }
  ],
  studies: [
    { text: "{{target}}, ton niveau d'attention rivalise avec celui d'un poisson rouge.", intensity: 'light', context: 'studies' },
    { text: "{{target}}, tu es le roi/la reine de la procrastination académique.", intensity: 'medium', context: 'studies' },
    { text: "{{target}}, même les calculatrices sont plus intelligentes que toi.", intensity: 'light', context: 'studies' },
    { text: "{{target}}, ton cerveau a la capacité de stockage d'une disquette.", intensity: 'medium', context: 'studies' },
    { text: "{{target}}, tu es le spécialiste des 'j'ai oublié de faire mes devoirs'.", intensity: 'light', context: 'studies' },
    { text: "{{target}}, même les manuels scolaires s'ennuient avec toi.", intensity: 'medium', context: 'studies' },
    { text: "{{target}}, tu es plus concentré qu'un écran de veille.", intensity: 'light', context: 'studies' },
    { text: "{{target}}, ton QI a la température d'un congélateur.", intensity: 'medium', context: 'studies' },
    { text: "{{target}}, tu es le champion du monde de l'oubli sélectif.", intensity: 'light', context: 'studies' },
    { text: "{{target}}, même les crayons ont plus de pointe que toi.", intensity: 'medium', context: 'studies' }
  ],
  auto: [
    { text: "{{target}}, tu conduis plus lentement qu'un tracteur en panne.", intensity: 'light', context: 'auto' },
    { text: "{{target}}, même les vélos te doublent sur l'autoroute.", intensity: 'medium', context: 'auto' },
    { text: "{{target}}, tu es le roi/la reine des créneaux ratés.", intensity: 'light', context: 'auto' },
    { text: "{{target}}, ton code de la route est plus flexible qu'un élastique.", intensity: 'medium', context: 'auto' },
    { text: "{{target}}, tu es le spécialiste des 'j'avais pas vu le panneau'.", intensity: 'light', context: 'auto' },
    { text: "{{target}}, même les piétons arrivent avant toi.", intensity: 'medium', context: 'auto' },
    { text: "{{target}}, tu es plus prudent qu'un escargot en armure.", intensity: 'light', context: 'auto' },
    { text: "{{target}}, ton permis de conduire est plus fictif qu'un roman.", intensity: 'medium', context: 'auto' },
    { text: "{{target}}, tu es le champion du monde des embouteillages.", intensity: 'light', context: 'auto' },
    { text: "{{target}}, même les feux rouges s'ennuient avec toi.", intensity: 'medium', context: 'auto' }
  ],
  tech: [
    { text: "{{target}}, ton code a plus de bugs qu'un zoo.", intensity: 'light', context: 'tech' },
    { text: "{{target}}, même les ordinateurs se moquent de toi.", intensity: 'medium', context: 'tech' },
    { text: "{{target}}, tu es le roi/la reine des 'ça marchait sur ma machine'.", intensity: 'light', context: 'tech' },
    { text: "{{target}}, ton niveau de programmation rivalise avec celui d'un hamster.", intensity: 'medium', context: 'tech' },
    { text: "{{target}}, tu es le spécialiste des 'j'ai pas testé mais ça devrait marcher'.", intensity: 'light', context: 'tech' },
    { text: "{{target}}, même les algorithmes simples te donnent du fil à retordre.", intensity: 'medium', context: 'tech' },
    { text: "{{target}}, tu es plus obsolète qu'un Windows 95.", intensity: 'light', context: 'tech' },
    { text: "{{target}}, ton debug consiste à redémarrer et prier.", intensity: 'medium', context: 'tech' },
    { text: "{{target}}, tu es le champion du monde des 'copy-paste' maladroits.", intensity: 'light', context: 'tech' },
    { text: "{{target}}, même les robots ont plus de logique que toi.", intensity: 'medium', context: 'tech' }
  ],
  lifestyle: [
    { text: "{{target}}, ton organisation ressemble à un tiroir de chaussettes.", intensity: 'light', context: 'lifestyle' },
    { text: "{{target}}, même les plantes d'intérieur ont plus de vie que toi.", intensity: 'medium', context: 'lifestyle' },
    { text: "{{target}}, tu es le roi/la reine de la procrastination créative.", intensity: 'light', context: 'lifestyle' },
    { text: "{{target}}, ton planning a la cohérence d'un puzzle incomplet.", intensity: 'medium', context: 'lifestyle' },
    { text: "{{target}}, tu es le spécialiste des 'je le ferai demain'.", intensity: 'light', context: 'lifestyle' },
    { text: "{{target}}, même les horloges s'ennuient avec toi.", intensity: 'medium', context: 'lifestyle' },
    { text: "{{target}}, tu es plus prévisible qu'un épisode de télé-réalité.", intensity: 'light', context: 'lifestyle' },
    { text: "{{target}}, ton rythme de vie rivalise avec celui d'un escargot.", intensity: 'medium', context: 'lifestyle' },
    { text: "{{target}}, tu es le champion du monde de l'improvisation permanente.", intensity: 'light', context: 'lifestyle' },
    { text: "{{target}}, même les calendriers se perdent avec toi.", intensity: 'medium', context: 'lifestyle' }
  ]
}

export const contextTemplatesEn: Record<string, Template[]> = {
  gym: [
    { text: "{{target}}, your favorite PR is 'Nothing More'.", intensity: 'light', context: 'gym' },
    { text: "{{target}}, even dumbbells mock you.", intensity: 'medium', context: 'gym' },
    { text: "{{target}}, you're the king/queen of gym excuses.", intensity: 'light', context: 'gym' },
    { text: "{{target}}, your cardio consists of climbing escalators.", intensity: 'medium', context: 'gym' },
    { text: "{{target}}, you're more flexible than a used rubber band.", intensity: 'light', context: 'gym' },
    { text: "{{target}}, even treadmills get bored with you.", intensity: 'medium', context: 'gym' },
    { text: "{{target}}, you're the specialist of 30-minute 'active rests'.", intensity: 'light', context: 'gym' },
    { text: "{{target}}, your workout plan fits on a Post-it.", intensity: 'medium', context: 'gym' },
    { text: "{{target}}, you're more flexible than a stick of dynamite.", intensity: 'light', context: 'gym' },
    { text: "{{target}}, even free weights have more freedom than you.", intensity: 'medium', context: 'gym' }
  ],
  gaming: [
    { text: "{{target}}, even NPCs have more initiative.", intensity: 'light', context: 'gaming' },
    { text: "{{target}}, you're the king/queen of rage quit.", intensity: 'medium', context: 'gaming' },
    { text: "{{target}}, your K/D ratio is lower than your IQ.", intensity: 'light', context: 'gaming' },
    { text: "{{target}}, even bots play better than you.", intensity: 'medium', context: 'gaming' },
    { text: "{{target}}, you're the specialist of 'lag excuses'.", intensity: 'light', context: 'gaming' },
    { text: "{{target}}, your skill cap is at ground level.", intensity: 'medium', context: 'gaming' },
    { text: "{{target}}, you're more toxic than radioactive waste.", intensity: 'light', context: 'gaming' },
    { text: "{{target}}, even noobs give you lessons.", intensity: 'medium', context: 'gaming' },
    { text: "{{target}}, you're the world champion of AFK.", intensity: 'light', context: 'gaming' },
    { text: "{{target}}, your gameplay looks like a permanent glitch.", intensity: 'medium', context: 'gaming' }
  ],
  studies: [
    { text: "{{target}}, your attention span rivals that of a goldfish.", intensity: 'light', context: 'studies' },
    { text: "{{target}}, you're the king/queen of academic procrastination.", intensity: 'medium', context: 'studies' },
    { text: "{{target}}, even calculators are smarter than you.", intensity: 'light', context: 'studies' },
    { text: "{{target}}, your brain has the storage capacity of a floppy disk.", intensity: 'medium', context: 'studies' },
    { text: "{{target}}, you're the specialist of 'I forgot to do my homework'.", intensity: 'light', context: 'studies' },
    { text: "{{target}}, even textbooks get bored with you.", intensity: 'medium', context: 'studies' },
    { text: "{{target}}, you're more focused than a screensaver.", intensity: 'light', context: 'studies' },
    { text: "{{target}}, your IQ has the temperature of a freezer.", intensity: 'medium', context: 'studies' },
    { text: "{{target}}, you're the world champion of selective forgetting.", intensity: 'light', context: 'studies' },
    { text: "{{target}}, even pencils have more point than you.", intensity: 'medium', context: 'studies' }
  ],
  auto: [
    { text: "{{target}}, you drive slower than a broken tractor.", intensity: 'light', context: 'auto' },
    { text: "{{target}}, even bicycles overtake you on the highway.", intensity: 'medium', context: 'auto' },
    { text: "{{target}}, you're the king/queen of failed parking attempts.", intensity: 'light', context: 'auto' },
    { text: "{{target}}, your traffic code is more flexible than a rubber band.", intensity: 'medium', context: 'auto' },
    { text: "{{target}}, you're the specialist of 'I didn't see the sign'.", intensity: 'light', context: 'auto' },
    { text: "{{target}}, even pedestrians arrive before you.", intensity: 'medium', context: 'auto' },
    { text: "{{target}}, you're more cautious than a snail in armor.", intensity: 'light', context: 'auto' },
    { text: "{{target}}, your driver's license is more fictional than a novel.", intensity: 'medium', context: 'auto' },
    { text: "{{target}}, you're the world champion of traffic jams.", intensity: 'light', context: 'auto' },
    { text: "{{target}}, even red lights get bored with you.", intensity: 'medium', context: 'auto' }
  ],
  tech: [
    { text: "{{target}}, your code has more bugs than a zoo.", intensity: 'light', context: 'tech' },
    { text: "{{target}}, even computers mock you.", intensity: 'medium', context: 'tech' },
    { text: "{{target}}, you're the king/queen of 'it worked on my machine'.", intensity: 'light', context: 'tech' },
    { text: "{{target}}, your programming level rivals that of a hamster.", intensity: 'medium', context: 'tech' },
    { text: "{{target}}, you're the specialist of 'I didn't test it but it should work'.", intensity: 'light', context: 'tech' },
    { text: "{{target}}, even simple algorithms give you trouble.", intensity: 'medium', context: 'tech' },
    { text: "{{target}}, you're more obsolete than Windows 95.", intensity: 'light', context: 'tech' },
    { text: "{{target}}, your debugging consists of restarting and praying.", intensity: 'medium', context: 'tech' },
    { text: "{{target}}, you're the world champion of clumsy copy-paste.", intensity: 'light', context: 'tech' },
    { text: "{{target}}, even robots have more logic than you.", intensity: 'medium', context: 'tech' }
  ],
  lifestyle: [
    { text: "{{target}}, your organization looks like a sock drawer.", intensity: 'light', context: 'lifestyle' },
    { text: "{{target}}, even houseplants have more life than you.", intensity: 'medium', context: 'lifestyle' },
    { text: "{{target}}, you're the king/queen of creative procrastination.", intensity: 'light', context: 'lifestyle' },
    { text: "{{target}}, your schedule has the coherence of an incomplete puzzle.", intensity: 'medium', context: 'lifestyle' },
    { text: "{{target}}, you're the specialist of 'I'll do it tomorrow'.", intensity: 'light', context: 'lifestyle' },
    { text: "{{target}}, even clocks get bored with you.", intensity: 'medium', context: 'lifestyle' },
    { text: "{{target}}, you're more predictable than a reality TV show.", intensity: 'light', context: 'lifestyle' },
    { text: "{{target}}, your pace of life rivals that of a snail.", intensity: 'medium', context: 'lifestyle' },
    { text: "{{target}}, you're the world champion of permanent improvisation.", intensity: 'light', context: 'lifestyle' },
    { text: "{{target}}, even calendars get lost with you.", intensity: 'medium', context: 'lifestyle' }
  ]
}
